### ISSUE TITLE
Limitation in "How to accumulate? Calculate "Mean". 

### ISSUE THREAD

**Issue by R180** [sjentsch/jTransform#2]
Hi. I believe there's a significant limitation in "_How to accumulate? Calculate Mean_". The underlying code appears not to include _na.rm=TRUE_ when calculating the mean. Therefore, for example, despite each person (unit) containing some data in each of three repeated-measures cells, the result is NA if any of the to-be-averaged values are NA. See the screen shot, below.

![image](https://github.com/sjentsch/jTransform/assets/16230091/e85521ea-5588-4a1f-8090-448c87a3cdbd)

**Comment by sjentsch** [comment]
Thanks for reporting. It is fixed now and should appear soon in the jamovi library.

**Comment by sjentsch** [comment]
![image](https://github.com/sjentsch/jTransform/assets/37706914/e6fe5224-e175-4b49-b623-554b634ea8f6)
